#!/usr/bin/env zsh

# Get OS X software updates
sudo softwareupdate --all --install --force

brew-update

skhd --start-service
yabai --start-service

# npm
npm i -g npm

# Update zinit and plugins
zinit self-update

# Reload zsh env
/usr/local/bin/zsh -l
