#!/usr/bin/env zsh

# Get OS X software updates
sudo softwareupdate --all --install --force

brew-update

skhd --start-service
yabai --start-service

# npm
npm i -g npm

# rvm
# rvm get stable

# gem
# sudo gem update --system
# sudo gem update

# (cd ~/.tmux/plugins/tpm && git pull)

# Update zsh plugins
zi update

# Reload zsh env
#reload
/usr/local/bin/zsh -l

